backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

site_url: https://bluroaadmin.netlify.app
display_url: https://bluroacafe.com

collections:
  - name: "site"
    label: "Site Content"
    files:
      - label: "Global Content"
        name: "global"
        file: "data/site.json"
        fields:
          - { label: "Site Name", name: "siteName", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }

  - name: "menu"
    label: "Menu"
    folder: "data/menu"
    create: true
    extension: "json"
    format: "json"
    slug: "{{category}}"

    fields:
      - label: "Category"
        name: "category"
        widget: "string"

      - label: "Menu Items"
        name: "items"
        widget: "list"
        summary: "{{fields.name}} â€” {{fields.price}}"
        fields:
          - { label: "Item Name", name: "name", widget: "string" }
          - { label: "Price", name: "price", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
